[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  NETLIFY_USE_YARN = "false"
  NODE_OPTIONS = "--enable-source-maps"

[[plugins]]
  package = "@netlify/plugin-gatsby"
