[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "16.18.0"
  NPM_VERSION = "8.19.2"
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-gatsby"
